//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string Productcode { get; set; }
        public string Productname { get; set; }
        public Nullable<int> Quantityperunit { get; set; }
        public Nullable<int> Unitinstock { get; set; }
        public Nullable<decimal> Unitprice { get; set; }
        public Nullable<int> Discount { get; set; }
        public string Picture { get; set; }
        public string PicturePath { get; set; }
        public Nullable<int> SizeID { get; set; }
        public Nullable<int> CaterogyID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Sizer Sizer { get; set; }
    }
}
